### ISSUE TITLE
Paths not updated before build

### ISSUE THREAD

**Issue by HamzaRino** [NibbleByte/UnitySceneReference#2]
Hi there, thanks for maintaining this great fork of SceneReference.

The readme states the following:

> Paths are updated during build (guaranteed by the [ISerializationCallbackReceiver](https://docs.unity3d.com/ScriptReference/ISerializationCallbackReceiver.html)).

However my tests with the original SceneReference show that it does not handle path changes, renaming or moving scenes.

Could you confirm if it should work?
And if so how does `ISerializationCallbackReceiver` achieve this?

**Comment by NibbleByte** [comment]
Hello,

You can check out the whole repository - it is a Unity project with some
test setup. Basically I have a starter scene in which with hotkeys 1 to 5
it loads other scenes by SceneReferences.
In this starter scene, I use SceneReferences to other scenes in a scene
GameObject field, in a prefab and in a ScriptableObject.
[image: image.png]
If I go and rename all target scenes, make a build and try out the hotkeys,
it does seem to work.
As far as I remember, when Unity builds scenes it opens each one of them
and serializes them to bundles. While doing this it calls
"OnBeforeSerialize()" on objects which updates the scene paths.

If you know some other ways this could fail, please let me know. It would
be best if you give me some reproduction steps.
For example - I haven't tested if this works with bundled scenes
(Addressables or similar).

Cheers :)

**Comment by HamzaRino** [comment]
Hi,

thanks a lot for getting back to me so quickly and taking the time to reply and explain!
I will take a look at the rest of the repo and especially the tests.

I will also do more tests from my side.

We are mainly using a modified version of the original SceneReference in ScriptableObjects.
So maybe your `_isDirty` flag trick could help.
Also I am delaying the login in both `OnBeforeSerialize` and `OnAfterSerialize`, otherwise I get an error due to a Unity API that should not take place at that stage.

We had issues (even recently) in our builds before when we renamed or moved scenes.
I will close this issue now if you don't mind.

Stay safe!
